AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for queue based app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloSqsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        MySqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10
            Enabled: true

  MySqsQueue:
    Type: AWS::SQS::Queue

Outputs:
  HelloSqsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloSqsFunction.Arn
  HelloSqsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloSqsFunctionRole.Arn
